#! /bin/zsh

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
    export EDITOR='vim'
fi

# zoxide init
eval "$(zoxide init zsh)"

# bat config
# see: https://github.com/sharkdp/bat
export BAT_THEME="tokyonight_storm"
# use bat as manpager
export MANPAGER="sh -c 'sed -u -e \"s/\\x1B\[[0-9;]*m//g; s/.\\x08//g\" | bat -p -lman'"

# add extra paths
# export PATH=$(IFS=:; echo "${PATHS[*]}:$PATH")

# Oh My Zsh configuration.
export ZSH="$HOME/.oh-my-zsh"

source <(fzf --zsh)

plugins=(
    aliases # helps list the shortcuts that are currently available
    ansible
    aws
    brew
    chezmoi
    colorize # adds color to the output of certain commands
    conda
    direnv
    docker
    dotenv
    fast-syntax-highlighting
    gh
    git-commit
    git-flow
    gitfast
    golang
    helm
    history
    kubectl
    kubectx
    mise
    npm
    nvm
    opentofu
    poetry
    pyenv
    python
    rust
    terraform
    tmux
    zsh-autocomplete
    zsh-autosuggestions
    zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh
eval "$(starship init zsh)"

source "$HOME/.config/zsh/aliases.zsh"
source "$HOME/.config/zsh/functions.zsh"
source "$HOME/.config/zsh/fzf.zsh"
source "$HOME/.config/zsh/git.zsh"
source "$HOME/.config/zsh/theme.zsh"

# activate mise
eval "$(~/.local/bin/mise activate zsh)"

# load direnv
eval "$(direnv hook zsh)"

# bun completions
[ -s "/Users/eric/.bun/_bun" ] && source "/Users/eric/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

alias claude-mem='/Users/eric/.bun/bin/bun "/Users/eric/.claude/plugins/marketplaces/thedotmack/plugin/scripts/worker-service.cjs"'
